In [1]:
import pandas as pd
import numpy as np

In [ ]:
train_csv = pd.read_csv('train.csv')
train = train_csv.drop(columns='id')
print(train.head(0))


Empty DataFrame
Columns: [target, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, ...]
Index: []

[0 rows x 301 columns]


In [ ]:
X = np.array(train.drop(columns = 'target').values.tolist())
y = np.array(train['target'].values.tolist())
print(X.shape)
print(y.shape)

print(y)

(250, 300)
(250,)
[1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 0. 0. 1. 1. 0. 1. 1. 1. 1. 0. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 0. 1. 1. 1. 1.
 0. 0. 1. 1. 0. 1. 0. 1. 0. 1. 0. 0. 1. 1. 0. 0. 0. 1. 0. 1. 1. 1. 0. 1.
 1. 1. 1. 0. 1. 1. 0. 1. 1. 0. 0. 1. 1. 1. 0. 1. 1. 1. 1. 0. 1. 1. 1. 1.
 0. 1. 1. 1. 1. 0. 0. 1. 0. 1. 1. 0. 0. 1. 1. 1. 1. 1. 0. 1. 1. 0. 0. 1.
 0. 1. 0. 1. 0. 1. 0. 0. 0. 1. 1. 1. 1. 1. 0. 1. 0. 1. 1. 0. 1. 0. 1. 0.
 1. 1. 1. 1. 0. 1. 0. 1. 1. 0. 0. 1. 1. 0. 0. 1. 1. 0. 1. 1. 0. 1. 1. 1.
 0. 0. 0. 0. 0. 1. 1. 1. 1. 0. 0. 1. 1. 0. 0. 0. 1. 1. 1. 1. 1. 0. 1. 1.
 1. 0. 0. 1. 1. 1. 0. 1. 1. 0. 1. 1. 1. 0. 1. 0. 1. 0. 0. 0. 0. 1. 1. 0.
 1. 1. 0. 1. 1. 1. 1. 1. 1. 0. 1. 0. 0. 1. 1. 1. 1. 0. 0. 1. 1. 1. 1. 0.
 0. 1. 1. 0. 0. 0. 0. 0. 1. 0.]


In [ ]:
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5)

X_s = preprocessing.StandardScaler().fit(X).transform(X)
X_s_train, X_s_test, y_s_train, y_s_test = train_test_split(X_s, y, test_size=0.5)

X_n = preprocessing.Normalizer().fit(X).transform(X)
X_n_train, X_n_test, y_n_train, y_n_test = train_test_split(X_n, y, test_size=0.5)

In [ ]:
from sklearn import tree
from sklearn.model_selection import cross_val_score
from sklearn import svm
from sklearn.neural_network import MLPClassifier
from sklearn.linear_model import SGDClassifier
from sklearn.neighbors import (KNeighborsClassifier,NeighborhoodComponentsAnalysis)

In [ ]:
clf_tree = tree.DecisionTreeClassifier()
clf_raw = clf_tree.fit(X_train, y_train)
clf_s = clf_tree.fit(X_s_train,y_s_train)
clf_n = clf_tree.fit(X_n_train,y_n_train)

scores_raw = cross_val_score(clf_raw, X_test, y_test, cv=5)
scores_s = cross_val_score(clf_s, X_s_test, y_s_test, cv=5)
scores_n = cross_val_score(clf_n, X_n_test, y_n_test, cv=5)

print(scores_raw)
print("mean of raw dataset=",scores_raw.mean())
print(scores_s)
print("mean of standardized dataset=",scores_s.mean())
print(scores_n)
print("mean of normalized dataset=",scores_n.mean())


[0.6  0.6  0.56 0.48 0.64]
mean of raw dataset= 0.5760000000000001
[0.52 0.32 0.44 0.64 0.56]
mean of standardized dataset= 0.496
[0.4  0.48 0.48 0.6  0.48]
mean of normalized dataset= 0.488


In [ ]:
X_train, X_test, y_train, y_test = X_s_train, X_s_test, y_s_train, y_s_test

In [ ]:
clf_tree = tree.DecisionTreeClassifier()
clf_svm = svm.SVC()
clf_sgd = SGDClassifier(loss='log')
clf_knn = KNeighborsClassifier(n_neighbors=1)
clf_mlp = MLPClassifier()

In [ ]:
clf_tree = clf_tree.fit(X_train, y_train)
clf_svm = clf_svm.fit(X_train, y_train)
clf_sgd = clf_sgd.fit(X_train, y_train)
clf_knn = clf_knn.fit(X_train, y_train)
clf_mlp = clf_mlp.fit(X_train, y_train)

scores_tree = cross_val_score(clf_tree, X_test, y_test, cv=5)
scores_svm = cross_val_score(clf_svm, X_test, y_test, cv=5)
scores_sgd = cross_val_score(clf_sgd, X_test, y_test, cv=5)
scores_knn = cross_val_score(clf_knn, X_test, y_test, cv=5)
scores_mlp = cross_val_score(clf_mlp, X_test, y_test, cv=5)

print(clf_tree)
print(scores_tree)
print("mean=",scores_tree.mean())

print(clf_svm)
print(scores_svm)
print("mean=",scores_svm.mean())

print(clf_sgd)
print(scores_sgd)
print("mean=",scores_sgd.mean())

print(clf_knn)
print(scores_knn)
print("mean=",scores_knn.mean())

print(clf_mlp)
print(scores_mlp)
print("mean=",scores_mlp.mean())




DecisionTreeClassifier()
[0.72 0.48 0.6  0.52 0.52]
mean= 0.568
SVC()
[0.6  0.64 0.64 0.64 0.64]
mean= 0.632
SGDClassifier(loss='log')
[0.6  0.64 0.48 0.64 0.56]
mean= 0.584
KNeighborsClassifier(n_neighbors=1)
[0.48 0.56 0.72 0.72 0.52]
mean= 0.6
MLPClassifier()
[0.52 0.6  0.64 0.68 0.6 ]
mean= 0.6080000000000001


In [ ]:
clf_tree = tree.DecisionTreeClassifier()
clf_tree = clf_tree.fit(X_train, y_train)

In [ ]:
from sklearn.model_selection import GridSearchCV
parameters = {'kernel':('linear', 'poly', 'rbf', 'sigmoid'), 'C':[0.001, 0.01, 0.1, 1, 10, 100, 1000]}
svc = svm.SVC()
clf = GridSearchCV(svc, parameters)
clf.fit(X_train, y_train)
print(clf.best_score_, clf.best_params_)


0.7120000000000001 {'C': 0.1, 'kernel': 'linear'}


In [ ]:
parameters = {'n_neighbors':(1,2,3,4,5,6,7,8,9,10)}
clf_knn = KNeighborsClassifier()
clf = GridSearchCV(clf_knn, parameters)
clf.fit(X_train, y_train)
print(clf.best_score_, clf.best_params_)


0.648 {'n_neighbors': 1}


In [ ]:
parameters = {'activation':('identity', 'logistic', 'tanh', 'relu'),'hidden_layer_sizes':(3,4,5,6,7,8,9,10,11,12,13,14,15)}
clf_mlp = MLPClassifier(max_iter=10000 )
clf = GridSearchCV(clf_mlp, parameters)
clf.fit(X_train, y_train)
print(clf.best_score_, clf.best_params_)

0.6160000000000001 {'activation': 'relu', 'hidden_layer_sizes': 13}


In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.feature_selection import SelectFromModel
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import VotingClassifier
from sklearn.svm import LinearSVC
clf_svm = Pipeline([
  ('feature_selection', SelectFromModel(LinearSVC(penalty="l1",dual=False, max_iter=10000))),
  ('classification', svm.SVC(kernel='linear'))
])
clf_sgd = Pipeline([
  ('feature_selection', SelectFromModel(LinearSVC(penalty="l1",dual=False, max_iter=10000))),SGDClassifier(loss='log')
])
clf_knn = Pipeline([
  ('feature_selection', SelectFromModel(LinearSVC(penalty="l1",dual=False, max_iter=10000))),KNeighborsClassifier(n_neighbors=1)
])
clf_mlp = Pipeline([
  ('feature_selection', SelectFromModel(LinearSVC(penalty="l1",dual=False, max_iter=10000))),MLPClassifier(hidden_layer_sizes=10, max_iter=10000 )
])
eclf = VotingClassifier(estimators=[('svm', clf_svm), ('sgd', clf_sgd), ('mlp', clf_mlp)], voting='soft')
clf_svm = clf_svm.fit(X_train, y_train)
clf_sgd = clf_sgd.fit(X_train, y_train)
clf_knn = clf_knn.fit(X_train, y_train)
clf_mlp = clf_mlp.fit(X_train, y_train)
eclf = eclf.fit(X_train, y_train)


TypeError: 'SGDClassifier' object is not iterable

In [ ]:
scaler = StandardScaler()

csv = pd.read_csv("test.csv")
x = pd.DataFrame(scaler.fit_transform(csv.drop(["id"], axis = 1)))

y_pred = pd.DataFrame({"ID": csv["id"], "Target": eclf.predict(x)})
y_pred.to_csv("submission.csv", index = False)