In [1]:
import pandas as pd
import numpy as np

In [2]:
train_csv = pd.read_csv('train.csv')
train = train_csv.drop(columns='id')
print(train.head(0))


Empty DataFrame
Columns: [target, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, ...]
Index: []

[0 rows x 301 columns]


In [3]:
X = np.array(train.drop(columns = 'target').values.tolist())
y = np.array(train['target'].values.tolist())
print(X.shape)
print(y.shape)

print(y)

(250, 300)
(250,)
[1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 0. 0. 1. 1. 0. 1. 1. 1. 1. 0. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 0. 1. 1. 1. 1.
 0. 0. 1. 1. 0. 1. 0. 1. 0. 1. 0. 0. 1. 1. 0. 0. 0. 1. 0. 1. 1. 1. 0. 1.
 1. 1. 1. 0. 1. 1. 0. 1. 1. 0. 0. 1. 1. 1. 0. 1. 1. 1. 1. 0. 1. 1. 1. 1.
 0. 1. 1. 1. 1. 0. 0. 1. 0. 1. 1. 0. 0. 1. 1. 1. 1. 1. 0. 1. 1. 0. 0. 1.
 0. 1. 0. 1. 0. 1. 0. 0. 0. 1. 1. 1. 1. 1. 0. 1. 0. 1. 1. 0. 1. 0. 1. 0.
 1. 1. 1. 1. 0. 1. 0. 1. 1. 0. 0. 1. 1. 0. 0. 1. 1. 0. 1. 1. 0. 1. 1. 1.
 0. 0. 0. 0. 0. 1. 1. 1. 1. 0. 0. 1. 1. 0. 0. 0. 1. 1. 1. 1. 1. 0. 1. 1.
 1. 0. 0. 1. 1. 1. 0. 1. 1. 0. 1. 1. 1. 0. 1. 0. 1. 0. 0. 0. 0. 1. 1. 0.
 1. 1. 0. 1. 1. 1. 1. 1. 1. 0. 1. 0. 0. 1. 1. 1. 1. 0. 0. 1. 1. 1. 1. 0.
 0. 1. 1. 0. 0. 0. 0. 0. 1. 0.]


In [4]:
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler


In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5)

X_s = preprocessing.StandardScaler().fit(X).transform(X)
X_s_train, X_s_test, y_s_train, y_s_test = train_test_split(X_s, y, test_size=0.5)

X_n = preprocessing.Normalizer().fit(X).transform(X)
X_n_train, X_n_test, y_n_train, y_n_test = train_test_split(X_n, y, test_size=0.5)

In [6]:
from sklearn import tree
from sklearn.model_selection import cross_val_score
from sklearn import svm
from sklearn.neural_network import MLPClassifier
from sklearn.linear_model import SGDClassifier
from sklearn.neighbors import (KNeighborsClassifier,NeighborhoodComponentsAnalysis)

In [7]:
clf_tree = tree.DecisionTreeClassifier()
clf_raw = clf_tree.fit(X_train, y_train)
clf_s = clf_tree.fit(X_s_train,y_s_train)
clf_n = clf_tree.fit(X_n_train,y_n_train)

scores_raw = cross_val_score(clf_raw, X_test, y_test, cv=5)
scores_s = cross_val_score(clf_s, X_s_test, y_s_test, cv=5)
scores_n = cross_val_score(clf_n, X_n_test, y_n_test, cv=5)

print(scores_raw)
print("mean of raw dataset=",scores_raw.mean())
print(scores_s)
print("mean of standardized dataset=",scores_s.mean())
print(scores_n)
print("mean of normalized dataset=",scores_n.mean())


[0.48 0.68 0.48 0.44 0.56]
mean of raw dataset= 0.528
[0.68 0.6  0.6  0.68 0.48]
mean of standardized dataset= 0.608
[0.68 0.72 0.52 0.52 0.44]
mean of normalized dataset= 0.576


In [8]:
X_train, X_test, y_train, y_test = X_s_train, X_s_test, y_s_train, y_s_test

In [9]:
clf_tree = tree.DecisionTreeClassifier()
clf_svm = svm.SVC()
clf_sgd = SGDClassifier(loss='log')
clf_knn = KNeighborsClassifier(n_neighbors=1)
clf_mlp = MLPClassifier()

In [10]:
clf_tree = clf_tree.fit(X_train, y_train)
clf_svm = clf_svm.fit(X_train, y_train)
clf_sgd = clf_sgd.fit(X_train, y_train)
clf_knn = clf_knn.fit(X_train, y_train)
clf_mlp = clf_mlp.fit(X_train, y_train)

scores_tree = cross_val_score(clf_tree, X_test, y_test, cv=5)
scores_svm = cross_val_score(clf_svm, X_test, y_test, cv=5)
scores_sgd = cross_val_score(clf_sgd, X_test, y_test, cv=5)
scores_knn = cross_val_score(clf_knn, X_test, y_test, cv=5)
scores_mlp = cross_val_score(clf_mlp, X_test, y_test, cv=5)

print(clf_tree)
print(scores_tree)
print("mean=",scores_tree.mean())

print(clf_svm)
print(scores_svm)
print("mean=",scores_svm.mean())

print(clf_sgd)
print(scores_sgd)
print("mean=",scores_sgd.mean())

print(clf_knn)
print(scores_knn)
print("mean=",scores_knn.mean())

print(clf_mlp)
print(scores_mlp)
print("mean=",scores_mlp.mean())




DecisionTreeClassifier()
[0.64 0.64 0.52 0.6  0.32]
mean= 0.5439999999999999
SVC()
[0.6  0.6  0.6  0.64 0.64]
mean= 0.616
SGDClassifier(loss='log')
[0.64 0.68 0.52 0.6  0.76]
mean= 0.64
KNeighborsClassifier(n_neighbors=1)
[0.48 0.64 0.52 0.64 0.68]
mean= 0.5920000000000001
MLPClassifier()
[0.6  0.52 0.6  0.56 0.76]
mean= 0.608


In [11]:
clf_tree = tree.DecisionTreeClassifier()
clf_tree = clf_tree.fit(X_train, y_train)

In [12]:
from sklearn.model_selection import GridSearchCV
parameters = {'kernel':('linear', 'poly', 'rbf', 'sigmoid'), 'C':[0.001, 0.01, 0.1, 1, 10, 100, 1000]}
svc = svm.SVC()
clf = GridSearchCV(svc, parameters)
clf.fit(X_train, y_train)
print(clf.best_score_, clf.best_params_)


0.712 {'C': 1, 'kernel': 'sigmoid'}


In [13]:
parameters = {'n_neighbors':(1,2,3,4,5,6,7,8,9,10)}
clf_knn = KNeighborsClassifier()
clf = GridSearchCV(clf_knn, parameters)
clf.fit(X_train, y_train)
print(clf.best_score_, clf.best_params_)


0.616 {'n_neighbors': 7}


In [14]:
parameters = {'activation':('identity', 'logistic', 'tanh', 'relu'),'hidden_layer_sizes':(3,4,5,6,7,8,9,10,11,12,13,14,15)}
clf_mlp = MLPClassifier(max_iter=10000 )
clf = GridSearchCV(clf_mlp, parameters)
clf.fit(X_train, y_train)
print(clf.best_score_, clf.best_params_)

0.656 {'activation': 'relu', 'hidden_layer_sizes': 6}


In [17]:
from sklearn.ensemble import RandomForestClassifier

parameters = {'max_depth':(2,3,4,5),'n_estimators':(80, 90, 100, 110, 120)}
clf = RandomForestClassifier()
clf = GridSearchCV(clf, parameters)
clf.fit(X_train, y_train)
print(clf.best_score_, clf.best_params_)

0.688 {'max_depth': 3, 'n_estimators': 110}


In [31]:
parameters = {'loss':('hinge', 'log', 'modified_huber', 'perceptron')}
clf = SGDClassifier()
clf = GridSearchCV(clf, parameters)
clf.fit(X_train, y_train)
print(clf.best_score_, clf.best_params_)

0.68 {'loss': 'modified_huber'}


In [34]:
from sklearn.pipeline import Pipeline
from sklearn.feature_selection import SelectFromModel

from sklearn.ensemble import VotingClassifier
from sklearn.svm import LinearSVC

clf_rf =  RandomForestClassifier(max_depth=3, n_estimators= 110)
clf_svm = svm.SVC(kernel='sigmoid',probability=True)
clf_sgd =  SGDClassifier(loss='modified_huber')

"""
clf_knn = Pipeline([
  ('feature_selection', SelectFromModel(LinearSVC(penalty="l1",dual=False, max_iter=10000))),
  ('knn',KNeighborsClassifier(n_neighbors=7))
])
clf_mlp = Pipeline([
  ('feature_selection', SelectFromModel(LinearSVC(penalty="l1",dual=False, max_iter=10000))),
  ('MLP', MLPClassifier(hidden_layer_sizes=6, max_iter=10000 ))
])
clf_knn = clf_knn.fit(X_train, y_train)
clf_mlp = clf_mlp.fit(X_train, y_train)
"""

eclf = VotingClassifier(estimators=[('rf', clf_rf),('svm', clf_svm), ('sgd', clf_sgd)], voting='soft')
clf_rf = clf_rf.fit(X_train, y_train)
clf_svm = clf_svm.fit(X_train, y_train)
clf_sgd = clf_sgd.fit(X_train, y_train)

eclf = eclf.fit(X_train, y_train)


In [35]:
scaler = StandardScaler()

csv = pd.read_csv("test.csv")
x = pd.DataFrame(scaler.fit_transform(csv.drop(["id"], axis = 1)))

y_pred = pd.DataFrame({"ID": csv["id"], "Target": eclf.predict(x)})
y_pred.to_csv("submission.csv", index = False)